// <auto-generated />
using System;
using EtkinlikPaneli.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtkinlikPaneli.Migrations
{
    [DbContext(typeof(EtkinlikContext))]
    [Migration("20260604071814_IlkVeritabanı")]
    partial class IlkVeritabanı
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EtkinlikPaneli.Models.Katilim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KatilimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EtkinlikId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Katilimlar");
                });

            modelBuilder.Entity("EtkinlikPaneli.Models.etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EtkinlikAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Yer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("EtkinlikPaneli.Models.kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("kullanicilar");
                });

            modelBuilder.Entity("EtkinlikPaneli.Models.Katilim", b =>
                {
                    b.HasOne("EtkinlikPaneli.Models.etkinlik", "etkinlik")
                        .WithMany("Katilimlar")
                        .HasForeignKey("EtkinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtkinlikPaneli.Models.kullanici", "Kullanici")
                        .WithMany("Katilimlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("etkinlik");
                });

            modelBuilder.Entity("EtkinlikPaneli.Models.etkinlik", b =>
                {
                    b.Navigation("Katilimlar");
                });

            modelBuilder.Entity("EtkinlikPaneli.Models.kullanici", b =>
                {
                    b.Navigation("Katilimlar");
                });
#pragma warning restore 612, 618
        }
    }
}
